# Generated by Django 3.1.6 on 2021-10-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0003_signcustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakeorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.IntegerField(default=1)),
                ('quan', models.IntegerField(default=1)),
                ('addr', models.CharField(default='None', max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.CharField(default='None', max_length=150)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cakeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
