# Generated by Django 3.1.6 on 2021-10-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='None', max_length=50)),
                ('pin', models.CharField(default='None', max_length=30)),
                ('fss', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(default='None', max_length=30)),
                ('mobile', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='None', max_length=30)),
                ('address', models.CharField(default='None', max_length=50)),
                ('pin', models.CharField(default='None', max_length=30)),
                ('gst', models.CharField(default='None', max_length=15)),
                ('name', models.CharField(default='None', max_length=30)),
                ('mobile', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cakeitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='None', max_length=20)),
                ('name', models.CharField(default='None', max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('cimg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price500', models.IntegerField(blank=True, null=True)),
                ('price1', models.IntegerField(blank=True, default=None, null=True)),
                ('price2', models.IntegerField(blank=True, default=None, null=True)),
                ('price3', models.IntegerField(blank=True, default=None, null=True)),
                ('des', models.CharField(default='None', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
