# Generated by Django 3.1.6 on 2021-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeitem',
            name='des',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
