# Generated by Django 3.1.6 on 2021-10-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_auto_20211017_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='None', max_length=150)),
                ('pin', models.CharField(default='None', max_length=30)),
                ('name', models.CharField(default='None', max_length=30)),
                ('mobile', models.CharField(default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
