# Generated by Django 3.1.6 on 2021-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_signcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='signcustomer',
            name='yearlsub',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
